pipeline:
  name: CD-Digitalrig-Github
  identifier: CDDigitalrigGithub
  projectIdentifier: Harness_POC
  orgIdentifier: WiproPOC
  tags: {}
  variables:
    - name: TOSCA_API_URL
      type: String
      value: http://34.60.185.155:8080/run-tosca
  stages:
    - stage:
        name: Deploy Dev
        identifier: Deploy_App
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: NodeAppGitHubService
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: digitalrig_gar_registry
                          type: GoogleArtifactRegistry
                          spec:
                            version: <+input>
            gitBranch: main
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: DigitalRig-Dev-Rollout
                  identifier: DigitalRigDevRollout
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: digitalrig_dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: GKEclusterstandardconnector
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        when:
          pipelineStatus: Success
          condition: <+input>
    - stage:
        name: Dev_Approval
        identifier: Dev_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Dev Deployment Approval
                  identifier: Dev_Deployment_Approval
                  type: HarnessApproval
                  timeout: 1h
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - Dev_Approval_Group
                        - BA_approval_Group
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
        when:
          pipelineStatus: Success
          condition: <+input>
    - stage:
        name: Deploy QA
        identifier: Deploy_QA
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: NodeAppGitHubService
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: digitalrig_gar_registry
                          type: GoogleArtifactRegistry
                          spec:
                            version: <+input>
          environment:
            environmentRef: digitalrigqa
            deployToAll: false
            infrastructureDefinitions:
              - identifier: GKEclusterstandardconnector
          execution:
            steps:
              - step:
                  name: Rollout Deployment QA
                  identifier: Rollout_Deployment_QA
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        when:
          pipelineStatus: Success
          condition: <+input>
    - stage:
        name: Execute QA Test
        identifier: Test_and_Validate
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: Run Tosca Tests
                  identifier: Run_Tosca_Tests
                  spec:
                    url: <+pipeline.variables.TOSCA_API_URL>
                    method: POST
                    headers:
                      - key: Content-Type
                        value: application/json
                    inputVariables: []
                    outputVariables: []
                    requestBody: |-
                      {
                        "eventId": "<+secrets.getValue('tosca_event_id')>"
                      }
                  timeout: 3m
        tags: {}
    - stage:
        name: QA_Approval
        identifier: QA_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: QA Deployment Approval
                  identifier: QA_Deployment_Approval
                  type: HarnessApproval
                  timeout: 1h
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - QA_Approval_Group
                        - BA_approval_Group
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: PR Approval
        identifier: PR_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: QA Approval stage
                  identifier: QA_Approval_stage
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - QA_Group
                        - BA_approval_Group
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
        when:
          pipelineStatus: Success
          condition: <+input>
    - stage:
        name: BA-QA_Approval
        identifier: BAQA_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: BA-QA_approval
                  identifier: BAQA_approval
                  type: HarnessApproval
                  timeout: 1h
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - BA_approval_Group
                        - QA_Approval_Group
                      serviceAccounts:
                        - poc
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: Deploy to Prod
        identifier: Deploy_App1
        description: Canary Deployment to Production
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: NodeAppGitHubService
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: digitalrig_gar_registry
                          type: GoogleArtifactRegistry
                          spec:
                            version: <+input>
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: Canary_Deployment
                  steps:
                    - step:
                        type: K8sCanaryDeploy
                        name: Canary 33
                        identifier: Canary_20
                        spec:
                          skipDryRun: false
                          instanceSelection:
                            spec:
                              count: 1
                            type: Count
                        timeout: 10m
                    - step:
                        type: HarnessApproval
                        name: Approval-1
                        identifier: HarnessApproval
                        spec:
                          approvalMessage: Please review the following information and approve the pipeline progression
                          includePipelineExecutionHistory: true
                          isAutoRejectEnabled: false
                          approvers:
                            userGroups:
                              - _project_all_users
                            minimumCount: 1
                            disallowPipelineExecutor: false
                          approverInputs: []
                        timeout: 1d
                    - step:
                        type: K8sCanaryDeploy
                        name: Canary 66
                        identifier: Canary_66
                        spec:
                          skipDryRun: false
                          instanceSelection:
                            spec:
                              count: 2
                            type: Count
                        timeout: 10m
              - stepGroup:
                  name: Primary Deployment
                  identifier: Primary_Deployment
                  steps:
                    - step:
                        type: HarnessApproval
                        name: Approval-2
                        identifier: Approval2
                        spec:
                          approvalMessage: Please review the following information and approve the pipeline progression
                          includePipelineExecutionHistory: true
                          isAutoRejectEnabled: false
                          approvers:
                            userGroups:
                              - _project_all_users
                            minimumCount: 1
                            disallowPipelineExecutor: false
                          approverInputs: []
                        timeout: 1d
                    - step:
                        type: K8sRollingDeploy
                        name: Full Deployment
                        identifier: Full_Deployment
                        spec:
                          skipDryRun: false
                          pruningEnabled: true
                        timeout: 10m
              - stepGroup:
                  name: Canary Wrap Up
                  identifier: Canary_Wrap_Up
                  steps:
                    - step:
                        type: HarnessApproval
                        name: Approval-3
                        identifier: Approval3
                        spec:
                          approvalMessage: Please review the following information and approve the pipeline progression
                          includePipelineExecutionHistory: true
                          isAutoRejectEnabled: false
                          approvers:
                            userGroups:
                              - _project_all_users
                            minimumCount: 1
                            disallowPipelineExecutor: false
                          approverInputs: []
                        timeout: 1d
                    - step:
                        type: K8sCanaryDelete
                        name: CanaryDelete
                        identifier: CanaryDelete
                        spec: {}
                        timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Deployment
                  identifier: rollbackDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: true
          environment:
            environmentRef: digitalrig_prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: GKEclusterstandardconnector
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
